# CUSTOME COMMANDS ALIASES
alias ls="ls --color"
alias ..="cd .."
alias root="sudo -s"
alias ssh="ssh -v"
alias scp="scp -v"
alias pg="ps aux | grep"
alias ping="ping -c 4"
alias tree="tree -C"

# HISTORY SETTINGS
export HISTTIMEFORMAT='%F %T '
export HISTCONTROL=erasedups
export HISTCONTROL=ignoredups
export HISTCONTROL=ignorespace
export HISTIGNORE="pwd:history:ls:ls -lh:clear"

# UTF-8 TERMINAL SUPPORT IN LION
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# GREP
export GREP_COLOR="1;32"

# LOAD BASH COMPLETION DEFINITIONS
if [ -f /etc/bash_completion ]; then
  . /etc/bash_completion
fi

# NEW PROMPT
if(( $UID == 0 )); then
  export PS1="\e[1;31m\u\e[0m@\H \w >: "
else
  export PS1="\e[1;32m\u\e[0m@\H \w >: "
fi

# PERMISSIONS
umask 022
